concurrency:
  group: ${{ github.workflow }}

jobs:
  cleanup:
    name: 🧹 Cleanup
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: ./.github/actions/git-config

      - name: Backmerge main into dev
        run: |
          git fetch origin
          git checkout -b dev origin/dev
          git merge origin/main -m "chore(release): merge main back into dev after release"
          git push origin dev

    timeout-minutes: 5

  release:
    if: contains(github.event.head_commit.message, '/release/')
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: ./.github/actions/pnpm-install

      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        name: Release
        run: pnpm release

    timeout-minutes: 15

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
